// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5WocSd-oZEjMF0VHACB3OtWDk-If0yCk',
    appId: '1:854885921307:web:fd5a65eb5d67678de97ebe',
    messagingSenderId: '854885921307',
    projectId: 'mesclainvest-eda16',
    authDomain: 'mesclainvest-eda16.firebaseapp.com',
    storageBucket: 'mesclainvest-eda16.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzvqELgINaXmX9P_OTMTFOZhn-53xS7CE',
    appId: '1:854885921307:android:6c0a884594ec5621e97ebe',
    messagingSenderId: '854885921307',
    projectId: 'mesclainvest-eda16',
    storageBucket: 'mesclainvest-eda16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk3cIVXuFqoL3cUpA-r84VleY9xJx8OnM',
    appId: '1:854885921307:ios:74074c9ab0138115e97ebe',
    messagingSenderId: '854885921307',
    projectId: 'mesclainvest-eda16',
    storageBucket: 'mesclainvest-eda16.firebasestorage.app',
    iosBundleId: 'com.mesclainvest.mesclainvest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk3cIVXuFqoL3cUpA-r84VleY9xJx8OnM',
    appId: '1:854885921307:ios:74074c9ab0138115e97ebe',
    messagingSenderId: '854885921307',
    projectId: 'mesclainvest-eda16',
    storageBucket: 'mesclainvest-eda16.firebasestorage.app',
    iosBundleId: 'com.mesclainvest.mesclainvest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5WocSd-oZEjMF0VHACB3OtWDk-If0yCk',
    appId: '1:854885921307:web:2ba6ffa8a8e3a07fe97ebe',
    messagingSenderId: '854885921307',
    projectId: 'mesclainvest-eda16',
    authDomain: 'mesclainvest-eda16.firebaseapp.com',
    storageBucket: 'mesclainvest-eda16.firebasestorage.app',
  );
}
